name: Reusable Notion Sync

on:
  workflow_call:
    secrets:
      NOTION_API_KEY:
        required: true
      NOTION_DATABASE_ID:
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout .github repo
        uses: actions/checkout@v4
        with:
          repository: あなたのOrganization名/.github # 自分のJSファイルを読み込むため

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Notion SDK
        run: npm install @notionhq/client

      - name: Run Sync Script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          # 実行中のリポジトリ情報を渡す
          REPO_NAME: ${{ github.event.repository.name }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_STATE: ${{ github.event.issue.state }} # open か closed
        run: node scripts/notion-sync.js
